### ISSUE TITLE
Div don't have ID

### ISSUE THREAD

**Issue by Elikill58** [Azuriom/Plugin-Wiki#11]
In the Vote plugin, there is this:
![image](https://user-images.githubusercontent.com/17381066/180832047-86f2ad2a-dcf3-493a-b9fd-b570107dc0de.png)

It make very easy to find the page, and change css according to it.

But, in this plugin, there isn't the id field:

![image](https://user-images.githubusercontent.com/17381066/180832192-3efdb916-28dd-43f0-b495-b7e860738662.png)

So, we can't find it with css.

Can you add it ?

**Comment by MrMicky-FR** [comment]
Added in 1014c356592d2637433b82a1d877f03587f16b2c
