### ISSUE TITLE
Presentation text for categories

### ISSUE THREAD

**Issue by Skyz32** [Azuriom/Plugin-Wiki#14]
FR : Pouvoir ajouter un texte de présentation pour chacune des catégories du wiki afin d'aider l'utilisateur à mieux se repérer.

EN : To be able to add introductory text for each of the categories in the wiki to help the user find their way around.

**Comment by MrMicky-FR** [comment]
FR: Où ce texte devrait être affiché ?

EN: Where should the text be displayed?
