### ISSUE TITLE
Limitation table "content"

### ISSUE THREAD

**Issue by Brand-dev** [Azuriom/Plugin-Wiki#15]
Bonjour,
Ça serait bien de changer le type "TEXT" par "LONGTEXT" dans la table "CONTENT" afin d'éviter d'avoir des erreur 500 inutilement!

**Comment by MrMicky-FR** [comment]
Ce n’est pas prévu pour le moment étant donné que la limite supportée par TEXT est déjà très grande, mais après rien n’empêche de faire la modification dans la base de données du site

**Comment by Brand-dev** [comment]
Très grande?
Je pense que tu n'a pas de serveur et que tu n'a pas essayer, impossible de faire un wiki détaillé, vraiment bête comme réponse sachant que ça prend 1 seconde à changer dans le code 0 effort

**Comment by Brand-dev** [comment]
![unknown-11](https://user-images.githubusercontent.com/98712497/195819319-fba9222b-d03f-4ca6-a98f-560c7186d40d.png)

**Comment by MrMicky-FR** [comment]
Pour une seule page de wiki ça me semble effectivement être très grand, séparer en plusieurs pages/catégories me semble bien plus pratique, car ça devient vite énorme : https://demo.azuriom.com/page-2

Mais après rien n'empèche de changer dans la base de données encore une fois.

Concernant le "0 efforts", vu le temps que je prend à gérer le projer, je me passerait bien de ce genre de remarques. Surtout que le principe d'un CMS est de s'adapter au mieux à la majorité, car il est impossible de faire un système qui convient à tous les cas, donc de façon générale il y a des compromis  à faire.
