### ISSUE TITLE
Add custom svg to category

### ISSUE THREAD

**Issue by Edeksyioun** [Azuriom/Plugin-Wiki#16]
Hey !

FR : Pouvoir rajouter l'option de lier à une catégorie du wiki une icone svg (taille respectable pour pas tout casser bien-sûr) en plus des icônes bootstrap.

EN : Be able to add an option to link to a category of the wiki an svg icon (respectable size for not to break everything of course) in addition to the bootstrap icons.

Thank you for your work, have a great day !

**Comment by MrMicky-FR** [comment]
Mixing icons and custom images isn’t really efficient
