### ISSUE TITLE
YouTube Video embed

### ISSUE THREAD

**Issue by JamesBach93** [Azuriom/Plugin-Wiki#20]
It would be cool to get an abillity to implement YouTube Videos in Wiki Articles.
So its possible to make some "How to" Videos without clicking on an Link to go to the Video.

**Comment by MrMicky-FR** [comment]
This is already possible by using the HTML code editor (the `<>` button on the right) and inserting `<iframe>` tag (can be obtained by the the « Share » button on YouTube, in the « Embed » section)
