### ISSUE TITLE
Make spoiler for wiki threads

### ISSUE THREAD

**Issue by Loren013** [Azuriom/Plugin-Wiki#21]
![image](https://github.com/Azuriom/Plugin-Wiki/assets/92492952/9df42a66-b360-4d72-80aa-5ebeb0460c1a)

Something like that, spoiler, as simple as it is, so we can put some stuff inside of it

**Comment by MrMicky-FR** [comment]
This would be complicated to implement at the plugin level because of themes compatibility and lack of TinyMCE spoiler support 😕
