### ISSUE TITLE
Limit roles with access per page

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Wiki#23]
Currently we can configure roles that gain access by category, it would be interesting to implement this same feature per wiki/page we create.

For example, I have the **`Knowledge Base`** category with free access for everyone, even without registration.

However, I would like to configure the page/wiki **`Tips for players with privileges`** within this category, but with limited access to only a few roles on the site.

![image](https://github.com/Azuriom/Plugin-Wiki/assets/32937653/0f7147fa-d9db-4ae9-8793-f5fb8dc59e67)

**Comment by MrMicky-FR** [comment]
You can create sub-categories for some roles only, like `Knowledge Base for players with privileges`
