### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Ventrex** [Azuriom/Plugin-Wiki#25]
Since the last update all my pages give the error “ Internal Server Error”

**Comment by MrMicky-FR** [comment]
Please send the logs located in `storage/logs`

**Comment by Ventrex** [comment]
There is 1 older log file called laravel-2023-10-17.log

I also cleared the cache, but didn't work

**Comment by Ventrex** [comment]
This was our mistake. Someone made a subdomain with the name Wiki.
