### ISSUE TITLE
Add as many sub-categories as we want

### ISSUE THREAD

**Issue by 010sid** [Azuriom/Plugin-Wiki#27]
[FR]

je tente de créer des sous-catégories dans mon wiki (grâce au plugin Wiki) Dans le pannel admin ça fonctionne visuellement parlant par contre la sous-catégorie ne fonctionne pas vraiment...

Voilà quelques screens pour un peu mieux illustrer le problème :

Le premier screen montre un exemple de la hiérarchie que je souhaite avoir dans une partie du wiki, on voit bien que tout est en cascade.

Le second montre la catégorie "consommable" qui a comme catégorie parente, la catégorie "Items".. Jusque là tout va bien... sauf que dans la case "Lien" on retrouve que "https;//......../wiki/" au lieu de retrouver "https;//......../wiki/items/"

Vous l'aurez compris, pour la sous-sous-catégorie "Nourriture" on devrait normalement retrouver "https;//......../wiki/items/consommable"

Ah, aussi j'ai tenté d'ouvrir la page test01, elle amène vers https;//......../wiki/items/nourriture/test-01" sans passer par les autres catégories, elle court-circuite la hiérarchie quoi

![image](https://github.com/Azuriom/Plugin-Wiki/assets/64012787/0e6df34e-dbb6-4dc3-86bf-e2751083a662)

![image](https://github.com/Azuriom/Plugin-Wiki/assets/64012787/ca2ba416-930e-4484-a286-a4dee6451be1)

**Comment by MrMicky-FR** [comment]
Unfortunately we cannot change this as it would break all URLs for existing subcategories...
