### ISSUE TITLE
Disabled categories are still visible on the wiki

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Wiki#30]
Same issue reported on Plugin Shop: https://github.com/Azuriom/Plugin-Shop/issues/228

![image](https://github.com/user-attachments/assets/b883b384-5f90-40a4-ac07-9de6e5e879a4)

I deactivated a Wiki category that was within another category and it is still not removed from the site.

![image](https://github.com/user-attachments/assets/1eaef139-b40f-4b4b-b8e9-ffffa2519668)

**Comment by MrMicky-FR** [comment]
Fixed in 5b742b1156464d4408bad173b37c4362c5010200
